version: 2
updates:
  - package-ecosystem: "uv"
    directories:
      - "/ner"
      - "/apps/worker"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    cooldown:
      default-days: 7
    groups: # allow grouping multiple updates in a PR.  Major version bumps will get their own PR
      version-bumps:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      security:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    cooldown:
      default-days: 7
    groups: # allow grouping multiple updates in a PR.  Major version bumps will get their own PR
      version-bumps:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      security:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"

